import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored at build-time from node_modules/onnxruntime-web/dist
    "public/onnxruntime-web/**",
    // Generated by `supabase gen types typescript`
    "src/lib/database.types.ts",
  ]),
]);

export default eslintConfig;
